import type { NextPage } from "next";
import React, { useState, useEffect } from "react";
import { LinhaLivro } from "../componentes/LinhaLivro";
import styles from "../styles/Home.module.css";
import Livro from "../classes/modelo/Livro";
import Head from "next/head";
import { Menu } from "../componentes/Menu";

const LivroLista: NextPage = () => {
  const baseURL = "http://localhost:3000/api/livros";
  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState(false);

  const obterLivros = async () => {
    const response = await fetch(baseURL);
    const data = await response.json();
    return data;
  };

  const excluirLivro = async (codigo: number) => {
    const response = await fetch(`${baseURL}/${codigo}`, { method: "DELETE" });
    return response.ok;
  };

  const excluir = async (codigo: number) => {
    await excluirLivro(codigo);
    setCarregado(false);
  };

  useEffect(() => {
    if (!carregado) {
      obterLivros().then((data) => {
        setLivros(data);
        setCarregado(true);
      });
    }
  }, [carregado]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Lista de Livros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <Menu />
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>Lista de Livros</h1>
        <table className="table table-striped">
          <thead>
            <tr>
              <th>Código</th>
              <th>Título</th>
              <th>Autor</th>
              <th>ISBN</th>
              <th>Editora</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro) => (
              <LinhaLivro
                key={livro.codigo}
                livro={livro}
                excluir={() => excluir(livro.codigo)}
              />
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;
